"""Create word_analyses table

Revision ID: 1f0a2acfbc15
Revises: 
Create Date: 2025-02-12 23:54:24.540292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0a2acfbc15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('part_of_speech', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_analyses')
    # ### end Alembic commands ###
