"""Add JSON data column to word_analyses

Revision ID: 2042a9b79f0e
Revises: 1f0a2acfbc15
Create Date: 2025-02-13 00:03:04.246870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2042a9b79f0e'
down_revision = '1f0a2acfbc15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_analyses', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###
