"""drop verb column

Revision ID: 22b8d424c985
Revises: 2042a9b79f0e
Create Date: 2025-02-14 11:05:41.795468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22b8d424c985'
down_revision = '2042a9b79f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_progress')
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_index('ix_word_word')

    op.drop_table('word')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('word_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('word', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('search_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='word_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.create_index('ix_word_word', ['word'], unique=False)

    op.create_table('user_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('word_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('last_reviewed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], name='user_progress_word_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_progress_pkey')
    )
    # ### end Alembic commands ###
