"""drop part_of_speech column

Revision ID: 9bfc965717b9
Revises: 22b8d424c985
Create Date: 2025-02-14 11:10:30.712620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bfc965717b9'
down_revision = '22b8d424c985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_analyses', schema=None) as batch_op:
        batch_op.drop_column('part_of_speech')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part_of_speech', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
